#!/usr/bin/env bash
set -euxo pipefail

current_version=$(jq -r .version package.json)
latest_release=$(gh release view --json tagName --jq .tagName 2>/dev/null || echo "")
latest_release_version=${latest_release#v}

if [[ -n "$latest_release_version" && "$current_version" == "$latest_release_version" ]]; then
  latest_tag=$(git tag --list | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)

  if [[ -n "$latest_tag" ]]; then
    commits_since_release=$(git rev-list "$latest_tag"..HEAD --count)
    if [[ "$commits_since_release" -eq 0 ]]; then
      echo "No commits since $latest_tag"
      exit 0
    fi
    echo "Found $commits_since_release commits since $latest_tag"
  fi

  version=$(git cliff --bumped-version)
  if [[ "$version" == "$latest_tag" || "${version#v}" == "$current_version" ]]; then
    echo "Commits since $latest_tag do not require a version bump"
    exit 0
  fi

  changelog=$(git cliff --bump --unreleased | tail -n +2)
  if [[ -z "$changelog" || "$changelog" == '<!-- generated by git-cliff -->' ]]; then
    echo "No unreleased changes found"
    exit 0
  fi

  if [[ "${DRY_RUN:-1}" == 1 ]]; then
    echo "version: $version"
    echo "changelog: $changelog"
    exit 0
  fi

  git config user.name mise-en-dev
  git config user.email 123107610+mise-en-dev@users.noreply.github.com
  gh auth setup-git

  npm version "${version#v}" --no-git-tag-version
  git add package.json package-lock.json CHANGELOG.md
  git checkout -B release
  git commit -m "chore: release $version"
  git push origin release --force

  if gh pr create --title "chore: release $version" --body "$changelog" --label release; then
    echo "Created release PR"
  else
    gh pr edit release --title "chore: release $version" --body "$changelog"
    echo "Updated release PR"
  fi
elif [[ -n "$current_version" && "$current_version" != "$latest_release_version" ]]; then
  echo "Package v$current_version is newer than release ${latest_release:-<none>}"
  echo "The merge-triggered release workflow will publish it"
else
  echo "No action needed"
fi
